# -*- coding: utf-8 -*-
"""Accenture.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/Priwinn/a881b7b08f31bcb3764990da077e7e5c/accenture.ipynb
"""

from itertools import product
import time

def cyl(n,nop,npmax=4):
  primes=[1,2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97]
  primes.remove(nop)
  for i in range(len(primes)):
    primes[i]=str(primes[i])
  ops=['+','-','*']
  
  for np in range(2,npmax+1):
    aux=[primes]
    for i in range(1,np):
      aux.append(ops)
      aux.append(primes)
    combs=product(*aux)
    for comb in combs:
      r=''.join(comb)
      if eval(r)==n:
        
        return r,np

import time
start_time = time.time()

cyl(3453,5)
print("--- %s seconds ---" % (time.time() - start_time))


